### ISSUE TITLE
Support for several experiments

### ISSUE THREAD

**Issue by gambasconjamon** [nuxt-community/google-optimize-module#37]
Hello! I have been testing the module and looks like it works fine, but I dont know how would I be able to use two experiments at the same time. So I'm looking for something like this:

`<div
      v-if="$experiments[$exp.name] === 'background'"
      class="absolute w-12 h-12 z-50 m-auto top-0 pt-16 right-0 bg-red-300 left-0"
    >
      experimento background activo
    </div>
    <div
      v-if="$exp.name === 'text'"
      class="absolute w-12 h-12 z-50 m-auto top-0 pt-16 right-0 bg-red-300 left-0"
    >
      experimento texto activo
    </div>`

**Comment by hecktarzuli** [comment]
Users only get assigned 1 experiment at a time.  This protects your test data to make sure the results don't dilute each other.

**Comment by pi0** [comment]
Hi @gambasconjamon indeed as @hecktarzuli mentioned, we cannot mix experiments because they affect each other. However it is possible to assign  multiple varients of a same experiment (it is called multivariate test or MVT) for this you need to put `sections` with a number higher than 1 ([docs](https://github.com/nuxt-community/google-optimize-module#creating-an-experiment))
